"""remove audio name

Revision ID: 0f444fc7ecdb
Revises: c50d15d98411
Create Date: 2024-01-30 21:02:40.224947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f444fc7ecdb'
down_revision = 'c50d15d98411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio', 'audio_name')
    op.alter_column('books', 'book_file',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_file',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.add_column('audio', sa.Column('audio_name', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=30), nullable=True))
    # ### end Alembic commands ###
