"""initial

Revision ID: 1992b27f3f3b
Revises: 
Create Date: 2024-02-01 13:44:32.925709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1992b27f3f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio', 'audio_file',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('books', 'book_name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('books', 'book_file',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_file',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               nullable=True)
    op.alter_column('books', 'book_name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('audio', 'audio_file',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               nullable=True)
    # ### end Alembic commands ###
