"""book_image

Revision ID: 85fe72ab6477
Revises: e2922cefed4a
Create Date: 2024-03-09 11:57:51.186462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fe72ab6477'
down_revision = 'e2922cefed4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_image')
    # ### end Alembic commands ###
