"""audio name

Revision ID: a6332d69e9f2
Revises: 85fe72ab6477
Create Date: 2024-03-16 19:49:07.505945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6332d69e9f2'
down_revision = '85fe72ab6477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('audio_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio', 'audio_name')
    # ### end Alembic commands ###
