"""drop s3url4

Revision ID: a7d6b8f7e9dd
Revises: 
Create Date: 2024-02-12 09:24:33.947224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d6b8f7e9dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('Firstname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('Lastname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('country_of_residence', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_Firstname'), 'users', ['Firstname'], unique=False)
    op.create_index(op.f('ix_users_Lastname'), 'users', ['Lastname'], unique=False)
    op.create_index(op.f('ix_users_country_of_residence'), 'users', ['country_of_residence'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('book_file', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    op.create_table('audio',
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('audio_file', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_index(op.f('ix_audio_audio_id'), 'audio', ['audio_id'], unique=False)
    op.create_table('celery_result',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('audio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_index(op.f('ix_celery_result_table_id'), 'celery_result', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_celery_result_table_id'), table_name='celery_result')
    op.drop_table('celery_result')
    op.drop_index(op.f('ix_audio_audio_id'), table_name='audio')
    op.drop_table('audio')
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_country_of_residence'), table_name='users')
    op.drop_index(op.f('ix_users_Lastname'), table_name='users')
    op.drop_index(op.f('ix_users_Firstname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
