"""initial

Revision ID: c50d15d98411
Revises: 
Create Date: 2024-01-16 09:51:35.458537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50d15d98411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('Firstname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('Lastname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('country_of_residence', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_Firstname'), 'users', ['Firstname'], unique=False)
    op.create_index(op.f('ix_users_Lastname'), 'users', ['Lastname'], unique=False)
    op.create_index(op.f('ix_users_country_of_residence'), 'users', ['country_of_residence'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('book_file', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    op.create_table('audio',
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('audio_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('audio_file', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_index(op.f('ix_audio_audio_id'), 'audio', ['audio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_audio_id'), table_name='audio')
    op.drop_table('audio')
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_country_of_residence'), table_name='users')
    op.drop_index(op.f('ix_users_Lastname'), table_name='users')
    op.drop_index(op.f('ix_users_Firstname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
